import { raleway } from "@/constants/fonts/fonts";
import Header from "@/layout/components/header/header";
import Head from "next/head";
import { ReactNode} from "react";
import css from "../../layout.module.css";

interface LayoutProps {
    children: ReactNode;
}

const NotFoundLayout:React.FC<LayoutProps> = ({ children }) => {
    return (
        <>
            <Head>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <div className={`${css.content} ${raleway.className}`}>
                <Header />
                <main
                    className={css.main}
                >
                    {children}
                </main>
            </div>
        </>
    );
};


export default NotFoundLayout;
