import { raleway } from "@/constants/fonts/fonts";
import Chat from "@/layout/components/chat/chat";
import Footer from "@/layout/components/footer/footer";
import Header from "@/layout/components/header/header";
import MobileNavbar from "@/layout/components/mobile_navbar/mobile_navbar";
import Head from "next/head";
import { usePathname } from "next/navigation";
import { PropsWithChildren } from "react";
import css from "./layout.module.css";

const Layout = ({ children }: PropsWithChildren) => {
  const pathname = usePathname();

  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${css.content} ${raleway.className}`}>
        <Header />
        <main className={css.main}>{children}</main>

        <Footer />
        <div className={css.mobile_navbar}>
          <Chat />
          <MobileNavbar />
        </div>
      </div>
    </>
  );
};

export default Layout;
